name: NodeJS with Gulp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        gulp bundle --ship
        gulp package-solution --ship
        
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: sharepoint
        path: |
          sharepoint/solution
        
#     - name: Get O365 CLI
#       run: |
#         npm install -g @pnp/office365-cli
        
#     - name: Login
#       run: |
#         o365 login -t password -u ${{secrets.USERNAME}} -p ${{secrets.PASSWORD}}
        
#     - name: Add
#       run: |
#         o365 spo app add -p ~/work/sharepointci/sharepointci/sharepoint/solution/SharePointCI.sppkg --overwrite
        
#     - name: Deploy
#       run: |
#         o365 spo app deploy --name SharePointCI.sppkg
